# This file was generated by GoReleaser. DO NOT EDIT.
cask "aster" do
  name "aster"
  desc "Terminal file reader. Markdown, JSONL, diffs, and more."
  homepage "https://github.com/wildreason/reader"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aster"

  on_macos do
    on_intel do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_darwin_amd64.tar.gz"
      sha256 "5859384107ef1698b6a7bb21dfca3d1c4057050c2a57f06b203644ac0f892629"
    end
    on_arm do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_darwin_arm64.tar.gz"
      sha256 "2c8e5795a5de15d143e133ba4ffc998a04baed6b95ebba36d5afe3c9bb4b415d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_linux_amd64.tar.gz"
      sha256 "5406854a7d040b3b3bace8e302909fb6763ad31f3f07139984fd8b5d6a355da2"
    end
    on_arm do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_linux_arm64.tar.gz"
      sha256 "8caa88094e3933cbdfbc34210bdd01809e879038e8390877cdbd43f884e678a7"
    end
  end

  # No zap stanza required
end
