# This file was generated by GoReleaser. DO NOT EDIT.
cask "aster" do
  name "aster"
  desc "Terminal file reader. Markdown, JSONL, diffs, and more."
  homepage "https://github.com/wildreason/reader"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aster"

  on_macos do
    on_intel do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_darwin_amd64.tar.gz"
      sha256 "6671a12ae4dfba734e63a916e389a5bf27777ac8bc84e608039dda0b4b030e12"
    end
    on_arm do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_darwin_arm64.tar.gz"
      sha256 "c13031d4e0bdd835a747584505f8c65cb4c64013c20c85484d504bc6e63935ab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_linux_amd64.tar.gz"
      sha256 "59b507be60cc76e6cb02c3e1361bc6376a2d44b0f9b0773dd817022fe083c57b"
    end
    on_arm do
      url "https://github.com/wildreason/reader/releases/download/v#{version}/aster_#{version}_linux_arm64.tar.gz"
      sha256 "5ea1e47d94787a4f6c85991b0f327a811a01eb44742cf9fae7d8d3db168503b6"
    end
  end

  # No zap stanza required
end
